name: ML Data Preprocessing

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_workflow.txt

      - name: Run Preprocessing Script
        run: |
          python automate_Muhammad_Nauval_Faiq_Khilmi.py --input exam_score_prediction_raw.csv --output preprocessing/exam_score_prediction_preprocessing

      - name: Upload Preprocessed Data Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/exam_score_prediction_preprocessing/